/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sched;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void emptyIsEmpty() {
        PriorityQueue<Integer> classUnderTest = new PriorityQueue<Integer>();
        assertTrue(classUnderTest.isEmpty());
    }

    @Test
    void notEmpty() {
        PriorityQueue<Integer> classUnderTest = new PriorityQueue<Integer>();
        classUnderTest.enqueue(5);
        assertFalse(classUnderTest.isEmpty());
    }
}
